version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
